"""Core utilities and base classes for the automation framework."""

from .base_page import BasePage
from .config import Config
from .exceptions import (
    AssertionError,
    AutomationError,
    BrowserConnectionError,
    BrowserError,
    BrowserLaunchError,
    BrowserTimeoutError,
    ConfigurationError,
    DatabaseConnectionError,
    DatabaseError,
    DatabasePoolError,
    DatabaseQueryError,
    ElementAssertionError,
    ElementNotClickableError,
    ElementNotFoundError,
    ElementNotVisibleError,
    ElementStateError,
    InvalidConfigurationError,
    LocatorError,
    MissingConfigurationError,
    MultipleElementsFoundError,
    NavigationError,
    PageError,
    PageLoadError,
    PageNotReadyError,
    TestDataError,
    TestDataNotFoundError,
    TestDataValidationError,
    TimeoutAssertionError,
)
from .logger import Logger
from .utils import wait_until

__all__ = [
    "BasePage",
    "Config",
    "Logger",
    "wait_until",
    "AutomationError",
    "BrowserError",
    "BrowserLaunchError",
    "BrowserConnectionError",
    "BrowserTimeoutError",
    "PageError",
    "NavigationError",
    "PageLoadError",
    "PageNotReadyError",
    "LocatorError",
    "ElementNotFoundError",
    "ElementNotVisibleError",
    "ElementNotClickableError",
    "ElementStateError",
    "MultipleElementsFoundError",
    "DatabaseError",
    "DatabaseConnectionError",
    "DatabaseQueryError",
    "DatabaseTimeoutError",
    "DatabasePoolError",
    "ConfigurationError",
    "MissingConfigurationError",
    "InvalidConfigurationError",
    "TestDataError",
    "TestDataNotFoundError",
    "TestDataValidationError",
    "AssertionError",
    "ElementAssertionError",
    "TimeoutAssertionError",
]
